### ISSUE TITLE
Windows compatability

### ISSUE THREAD

**Issue by JamiePhonic** [EvanHahn/pushbullet-cli#10]
is this app compatable with windows?
i gave it a go, but all i get at the prompt is this (either as admin or standard user)
`File "C:\Python34\lib\site-packages\pushbullet_cli-0.1-py3.4.egg\pushbullet_cli\app.py", line 19
  oldmask = os.umask(077)`

**Comment by EvanHahn** [comment]
@r-darwish, could you take a look?

**Comment by r-darwish** [comment]
I'll check it out

**Comment by r-darwish** [comment]
This should be resolved now. Thank you for reporting.
